# Application Configuration
spring.application.name=FlightManagementSystem

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/FlightManagementSystem
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Configuration
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=1800000

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false
